### PR TITLE
Correct and test compiled comparison in package

### LINKED ISSUE #55: compare package interface is broken
* not changing directories leads to not finding the compare file
* the error message about the file not being found is very vague as decor sails on (i.e., we need to check file existence ourselves)
* the error about the number of compare function decorations us unhelpful - treat 0 and >1 separately

### PR DESCRIPTION
**Pull request by richfitz**
In trying to wire this up with sircovid it turned out I'd failed to test (or implement correctly) the package interface to this.

This has become a bit of an omnibus PR with a number of bugs and unpleasantnesses fixed:

* generated code no longer includes whitespace (in C++), with test
* moved away from glue for the odin substitution because it's escape behaviour mangled code (`))` became `)` because it was an exactly-doubled closing marker)
* generating the data struct constructor was broken if it contained more than one element
* odin_dust() did not work with compare function when the source was in a subdirectory

Fixes #55

### CODE REVIEW

File: R/generate_dust.R [hunk 1]
```diff
@@ -540,16 +562,39 @@ generate_dust_core_data <- function(dat) {
...
-odin_variable_transformer <- function(dat, rewrite) {
-  function(text, envir) {
+## It would be really nice to use glue for this but we can't disable
+## escaping whcih means that a '))' becomes ')' which results in
+## broken code. This approach is pretty ugly but should do the trick
+## for now.
+transform_compare_odin <- function(text, dat, rewrite) {
+  re <- "odin\\(\\s*([^) ]+)\\s*\\)"
+  i <- grep(re, text)
+  d <- gregexpr(re, text[i])
```
Comment (johnlees) [inline R/generate_dust.R:572]: What are `i` and `d`? The structure of text, and i and d derived from it are unclear to me here

File: tests/testthat/examples/compare_simple.cpp [hunk 2]
```diff
@@ -1,11 +1,12 @@
 // [[odin.dust::compare_data(observed = double)]]
+// [[odin.dust::compare_data(another = int)]]
```
Comment (johnlees) [inline tests/testthat/examples/compare_simple.cpp:2]: `another` is ignored/not used in this compare function?

**Review by johnlees — CHANGES_REQUESTED** [review]

File: tests/testthat/examples/compare_simple.cpp (hunk 2 above)
Comment (richfitz) [reply tests/testthat/examples/compare_simple.cpp:2]: yeah, I needed a second data element in order to trigger and fix a bug with multiple data elements (the constructor was put together without commas!). It's not used here though because the compare function is so stupid

File: R/generate_dust.R (hunk 1 above)
Comment (richfitz) [reply R/generate_dust.R]: I've cleared that up now - let me know if that's easier. There's quite a bit of bookkeeping unfortunately

Comment (johnlees) [reply R/generate_dust.R]: Yep, that's a lot easier to follow!

**Review by johnlees — APPROVED** [review]
